spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-gc7vz5fpb4ap2t5325o.mysql.cn-chengdu.rds.aliyuncs.com:3306/medicine_online_3?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: soft2213_group3
      password: soft2213_group3
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000






