spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://rm-bp1k3910p07nkttl93o.mysql.rds.aliyuncs.com:3306/1_medicine_online?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2b8
      username: rootmax
      password: Al731028@
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 30000






